# Gives a model a stable, non-enumerable public identifier used in the API and
# URLs (e.g. "proj_f8k2p9qd4m"). The integer primary key stays internal.
#
#   class Project < ApplicationRecord
#     has_public_id :proj
#   end
#
module HasPublicId
  extend ActiveSupport::Concern

  ALPHABET = ("a".."z").to_a.concat(("2".."9").to_a).freeze
  LENGTH = 12

  class_methods do
    def has_public_id(prefix)
      self.public_id_prefix = prefix.to_s

      before_validation :assign_public_id, on: :create
      validates :public_id, presence: true, uniqueness: true

      # Look up by public_id, falling back to nothing (never by raw pk).
      def self.find_by_public_id!(value)
        find_by!(public_id: value)
      end
    end
  end

  included do
    class_attribute :public_id_prefix, instance_writer: false
  end

  # Use the public id in URLs generated by Rails helpers.
  def to_param
    public_id
  end

  private

  def assign_public_id
    return if public_id.present?

    self.public_id = loop do
      candidate = "#{public_id_prefix}_#{Array.new(LENGTH) { HasPublicId::ALPHABET.sample }.join}"
      break candidate unless self.class.exists?(public_id: candidate)
    end
  end
end
